### ISSUE TITLE
Deleting Old meta Model in the object browser

### ISSUE THREAD

**Issue by AustriaTech** [FRAME-NEXT/FRAME#10]
Is anyone against the deletion of the initial meta model?
I coun't see any value of anymore.
![grafik](https://user-images.githubusercontent.com/60388823/100355323-d8737080-2ff1-11eb-8822-81b6d7b08dd4.png)

**Comment by Drees-BASt** [comment]
I am fine with it. If someone of us would really need an idea of how we got to our metamodel, it could be looked up in an older version. But for our further procedure, it is not needed anymore.

**Comment by mertaksac** [comment]
I also don't have any objections.
