### ISSUE TITLE
Discussing The Connectors Between Stakeholder, ... , User Needs

### ISSUE THREAD

**Issue by mertaksac** [FRAME-NEXT/FRAME#13]
The "motivational layer" could be thought as follows, starting with definition of the Stakeholders and ending with selection of the user needs.

![image](https://user-images.githubusercontent.com/71774192/101880754-7d6e7b80-3ba4-11eb-8521-59ff0df48867.png)

Existing connections on the FRAME_Metamodel

Source | Type | Target
-- | -- | --
Vision | defines | ITS Service
ITS Service | instantiate | mission   statement
Mission statement | Defines | User   Needs

Suggested Connections

Source | Type | Target
-- | -- | --
Stakeholder | defines | ITS   Vision
ITS   Vision | realized by | ITS   Mission Statement
ITS   Mission Statement | achieved by | ITS   Service
ITS   Service | corresponds to | User   Need

Note: Some "building blocks" from the wiki that may be considered to be part of the motivational layer such as "Desired architecture results" and "Business expectations" are disregarded in this picture on purpose. These artefacts are effective in describing the ITS Service and may have further effect in forming parts of the organizational view - roles etc. These parts were excluded since they were not full detailed in discussions between maintainers.

**Comment by mertaksac** [comment]
This issue was discussed in Maintainer's telco on 3 February 2020.

It was agreed to postpone discussion after C-ITS architecture is completed.

**Comment by AustriaTech** [comment]
Not relevant anymore due too development of the architecture.
