### ISSUE TITLE
Creating a "FRAME User Needs" navigation cell on the Landing Page

### ISSUE THREAD

**Issue by mertaksac** [FRAME-NEXT/FRAME#18]
It is proven to be a good practice to view the User Needs in Specification Manager.

![image](https://user-images.githubusercontent.com/71774192/105099948-92043480-5abd-11eb-8284-bdbae9920109.png)

The user may "open" the User Needs in Specification View, alternatively we could include a "FRAME User Needs" navigation cell in the Landing Page for the convenience of the user.

To do this, we should create a new diagram which has all User Needs and set this diagram property as: "always open as Specification".

And then we should link this diagram on the landing page as a navigation cell.

**Comment by AustriaTech** [comment]
May we should define the structure for the package "User architecture" at first.
The Link on the Landing Page is simple to archieve.

**Comment by mertaksac** [comment]
The user needs mentioned in this issue are the user needs in the FRAME Repository, and is not related to the "user architecture".

The main goal of adding such a navigation cell is to enable users to "browse" the user needs, investigate their relations with the low level functions before adding them to their architectures.

**Comment by Drees-BASt** [comment]
To me, this sounds like what Benjamin has proposed in #17 .

The approach sounds reasonable to me.

**Comment by mertaksac** [comment]
Here is a document elaborating on the original idea:
https://docs.google.com/document/d/1AKrETBibJXou7FuRq-QhdUTquPss4Lxo2CCH9mqNOGs

**Comment by mertaksac** [comment]
This issue was discussed in the Maintainer's Telco on 21st of January 2021.

It was decided to include a separate "landing page" (diagram) for the FRAME Repository on the main landing page and include the navigation cell for the User Needs on this diagram.

This was executed in the V4.43 of the FRAME Architecture Tool.

**Comment by mertaksac** [comment]
We agreed to have this navigation cell on FRAME Repository Landing Page

I have created 2 versions and uploaded them on AustriaTech Cloud.

The first version has the User Needs divided into User Need Groups, and the User Needs that are in these groups are listed in the related User Need Group's diagram.

The second version breaks down the User Need hierarchy in further details. User Need Groups are divided in User Need Services and they are divided in User Need Topics. The User Needs are listed only in the diagrams of the related User Need Topic's diagram.

![image](https://user-images.githubusercontent.com/71774192/106949806-84e27900-673e-11eb-8ca5-9b0217c2f4a7.png)


I also created 2 alternatives for the User Needs diagram, one with the navigation cells, and another with the additional "notes" of the User Needs Groups

![image](https://user-images.githubusercontent.com/71774192/106950721-dccdaf80-673f-11eb-8475-372726e539e7.png)


If you would kindly study the 2 versions of User Need Navigation and 2 alternatives of the User Need diagrams before the next maintainer's telco, we could finalize the discussion the topic before the V5 is published.

**Comment by Drees-BASt** [comment]
I vote for version 1 and alternative 2

**Comment by mertaksac** [comment]
The majority of the opinions were with the version 1 and the alternative 2.

This should be discussed / voted in one of the coming Maintainer's telcos and agreed before implemented for the V5 of our tool.

**Comment by mertaksac** [comment]
It was agreed to implement the version 1 and alternative 2.
I have created the ne User Needs package with this organization and sent it to Benjamin.
This issue is closed.
