### ISSUE TITLE
FRAME Toolbox TDF LowlevelFunction

### ISSUE THREAD

**Issue by AustriaTech** [FRAME-NEXT/FRAME#3]
I have downloaded the FRAME Toolbox and installed it.  However I have encountered some problems with it when I try to use it to modify an existing data flow diagram.

I need to add a data flow to data flow diagram F3.1.1.  The data flow is a low-level terminator data flow (TDFLL).  Using the “FRAME Toolbox” if I click on “TDFLL” and move the cursor into data flow diagram F3.1.1, I get the result shown in the attached picture “FRAME Toolbox TDF LowlevelFunction.png”.  But as you will see from the rest of the diagram, the shape is wrong – it implies to me that I am creating a function and not a data flow.

If I revert to the FRAME NEXT Technology toolbox, select “DFD Toolbox”, click on TDFLL and then move the cursor into data flow diagram F3.1.1. I get the result shown in the attached picture “FRAME NEXT Technology TDFLL.png”.  As you will see this is the correct shape that corresponds to all the other data flows in this and every other diagram.  Also it does not imply to me that I am creating a function.

I cannot find a way to convert the shape created using the “FRAME Toolbox” to the one using the “FRAME NEXT Technology toolbox”.  Do you know how to do this?

If a solution cannot be found we will have to continue to use the “FRAME NEXT Technology” toolbox for amendments to the existing data flow diagrams and any new data flow diagrams that are created as a result of future updates of the FRAME reference model.

Kind regards,

Richard

**Comment by mertaksac** [comment]
The shape of Data Flows in FRAME Toolbox was fixed in previous versions of the FRAME Architecture Tool.
This issue is closed.
