### ISSUE TITLE
Old FRAME Next Technology Toolbox is still in our Tool

### ISSUE THREAD

**Issue by mertaksac** [FRAME-NEXT/FRAME#32]
Will this toolbox be presented to the end user?
If no it should be removed.
We might want to create a EAPX file from scratch and import all the packages we want the user to access and the FRAME toolbox.

**Comment by AustriaTech** [comment]
The old Toolbox needs to be kept, aslong the FRAME Repository based on their defined stereotypes and connections.
After the transformation of the Repository we can delete the old Toolbox.
In the V5 Tool the old toolbox is set invisible

**Comment by mertaksac** [comment]
Thank you for the information.
