### ISSUE TITLE
eCall Mission Statement(s)

### ISSUE THREAD

**Issue by mertaksac** [FRAME-NEXT/FRAME#37]
eCall have 2 mission statements

1) Reduce the reaction times of road accidents in general in Europe for fast medical response and the overall reduction of road deaths.

2) Reduce follow up accidents on the road network through faster clearance of accidents.

The explanatory components are describing what would happen after successful implementation of these missions. Currently there are some requirements attached to the mission statements. These can be formulated as ITS Service (Descriptions)

**Comment by AustriaTech** [comment]
Thank you Mert.
The to parts are mentioned as added value in the motivational part.
But we will discus your proposal.
