### ISSUE TITLE
Some Low Level Functions are associated with Data Stores

### ISSUE THREAD

**Issue by mertaksac** [FRAME-NEXT/FRAME#63]
There is an association type connector between some low level functions and data stores.
so far I could only detect one between F3.1.4.4 and D3.9
and between F3.1.5.2 , F3.1.5.4 and D3.10

![image](https://user-images.githubusercontent.com/71774192/127155921-59d8c863-e745-4dc4-a3ae-10898a2afe04.png)

**Comment by burespe1** [comment]
There is cleanup necessary in the repository (we can make it in the database)

- there are connectors that connect interfaces and are not aggregations 

![image](https://user-images.githubusercontent.com/43144398/127163115-3c20bcbb-1ff2-4eae-a860-5c586e4e1637.png)

- purge different stereotypes for dataflows (TDF, TDFLL, TDFHL, Data_Flow, ...

- there are connectors that connect classes (functions) and are not aggregations 

![image](https://user-images.githubusercontent.com/43144398/127163464-5dc13f79-2a6e-4177-84b7-f99c6c44a0b8.png)

- connectors from datastores to functions 

![image](https://user-images.githubusercontent.com/43144398/127164218-647b993d-0b77-42ed-a8cb-65bdf8ca3a47.png)

- and vice versa (OK)

**Comment by bossomr** [comment]
It appears from the above that we have found some issues all of which are not directly related unless the relationship between the,m is that they both have something to do with changes needed to the Enterprise Architect database.

**Issue 1**: in the first issue from Mert, D3.10 is associated with F3.1.5.2 and F3.1.5.4, but it not connected to either of them with Data Flows.  This is also highlighted by Petr in the third screenshot he has produced.

**Assessment**: D3.10 is connected to F3.1.5.5 with Data Flows in DFD3.1.5 but is not associated with it according the "Links" part of its "Properties" window.  This can also be verified using the "Insert Related Elements" option in the drop-down menu for D3.10.  If the "Find relationships to" option is set to "2" in the "Insert Related Elements" window for D3.10 then F3.1.5.5 does appear, but at Level 2. 

F3.1.5.2 and F3.1.5.4 are both shown with an "Association" links in their according the "Links" parts of their "Properties" windows.

The MS Access database created for the old FRAME Selection Tool, only links Data Stores to Data Flows and hence to Low-level Functions, so I do not think this is much help.

I have also looked into the XML file produced by MEGA Process on which the import into Enterprise Architect has been based, but it is difficult to work out what information it contains.

To add to this issue, I looked at two other Data Stores, D3.12 and D3.4.  D3.12 is correctly linked to F3.2.6 but D3.4 is not linked to any Low-level Function.

**Conclusion**: I am not sure that there is a way to correct this problem with a script.  My thought is to create a diagram import every Data Store on to is and then go through and use "Insert Related Elements" for each one to make sure that each one is associated with its correct Low-level Function and correct when it is not.

**Issue 2**: in the first issue from Petr, there is a problem with Data Flow "mt.ptja_maintenance_information".

**Assessment**: I am not sure exactly what issue is being highlighted here.  The "Links" part of its "Properties" window it appears to me to be correct as does the content of its "Insert Related Elements" window.

The only issue I can find is that in the "Links" part of the "Properties" window for one of its component Data Flows "mt.ptja_roadworks_information_for_trip_monitoring" this Data Flow is shown as being being associated with F3.5., which also appears in its "Insert Related Elements" window in addition to the correct association with F3.5.8.   I do not know why this should be but it does not appear in DFD3 where F3.5 is shown?

**Conclusion**: I would delete the association of "mt.ptja_roadworks_information_for_trip_monitoring" in the "Links" part of its "Properties" window and run again whatever was used to generate the content of the screen shot.

**Issue 3**: in the second issue from Petr, EA_IMPORT_STUB appears.

**Assessment:** I do not know what this is?  It did appear when I did a search on the model in Enterprise Architect, but it did not appear to be in any package or diagram, or have anything other than itself in the "Links" part of its "Properties" window.

**Conclusion**: I guess it is something to do with the import activity.  According to its entry in the "search" window, it can be deleted, so I would do that and re-run the check again.

**Comment by burespe1** [comment]
Richard, thanks for the assessment.
I propose we go over the listed items and delete **them manually in E.A.**
I prefer this option since I do not want to mess with database more than absolutely necessary (since I do not know all the relations between tables = they are not shown in the database)

**Comment by bossomr** [comment]
Dear Petr,

 

Thank you for your e-mail and your suggestion.

 

I have started making the changes to remove all references to Sub-terminators and would like to finish these before we have a new version of the Enterprise Architect file.

 

Unless you have any objections I will delete the extra reference to F3.5 in “mt.ptja_roadworks_information_for_trip_monitoring”.  Obviously I do not know if there are any other similar extra references like this, unless that is that the analysis in your screen shot was showing.  I will also delete “EA_IMPORT_STUB” and will do as I have suggested and check all the associations for the Data Stores.  I hope I can complete this work by the end of this week and send it to Benjamin for Monday.

 

Kind regards,

 

Richard

 

 

Richard Bossom

Mobile Phone: +44 (0)7719196246 (voicemail available)

Skype ID: rapbossom

 

Richard Bossom ITS Consulting Limited.

Registered in England and Wales .  Registered Number: 07684384

Registered Office: Towngate House, 2-8 Parkstone Road , Poole, Dorset .  BH15 7TD

Postal Address: 6 Goldfinch Road, Creekmoor, Poole, Dorset, BH17 7TD, UK

The information contained in this email is confidential and intended solely for the addressee. Any access to this e-mail by anyone else is unauthorized. If you are not one of the intended recipients or have received this e-mail by mistake, please notify the sender immediately and delete this e-mail. Any unauthorized disclosure, copying or distribution of the material contained in this e-mail is strictly forbidden.

**Comment by AustriaTech** [comment]
Dear Petr,

 

Thank you for your e-mail.  I agree with your suggestion and have started on it today.

 

First I will look at the Data Stores, which I think should not have any links to any Functions.  The links should be to the Data Flows that connect them to Functions, which is true for many of them.  But it appears to be just a few that have links to Functions and not always those with which they exchange Data Flows.

 

Now that I have eliminated all references to Sub-terminators from the FRAME Repository, I think I know how to change the Sub-terminator stereotypes to Terminator stereotypes without touching the database.  It will be a bit complicated with possibly two copies of EA open at once, but I think it can be done.  Anyway I will try it out after I have finished with the Data Stores.

 

In case Mert is worried, I have not forgotten about the issue that he has raised.  But I would like to leave it until I have finished the two tasks I have outlined above.

 

Kind regards,

 

Richard

 

 

 

Richard Bossom

Mobile Phone: +44 (0)7719196246 (voicemail available)

Skype ID: rapbossom

 

Richard Bossom ITS Consulting Limited.

Registered in England and Wales .  Registered Number: 07684384

Registered Office: Towngate House, 2-8 Parkstone Road , Poole, Dorset .  BH15 7TD

Postal Address: 6 Goldfinch Road, Creekmoor, Poole, Dorset, BH17 7TD, UK

The information contained in this email is confidential and intended solely for the addressee. Any access to this e-mail by anyone else is unauthorized. If you are not one of the intended recipients or have received this e-mail by mistake, please notify the sender immediately and delete this e-mail. Any unauthorized disclosure, copying or distribution of the material contained in this e-mail is strictly forbidden.

**Comment by burespe1** [comment]
Dear Richard,

thanks. just quick observation:
Non repetitive tasks, like deleting an object (connector) might project to
more places in the database, that I would do manually in EA.
mundane repetitive tasks like "Steretype change" could be rally easily done
in the database  is really easy in the database MS Access, in the following
way (easy and already proven solution)
- change one in EA
- look at the projected change in database
- copy the change to other objects in database

Petr Bureš
email: ***@***.***
mob.: (+420) 777 131 603


čt 29. 7. 2021 v 11:09 odesílatel FRAME-NEXT ***@***.***>
napsal:

**Comment by mertaksac** [comment]
The connectors were deleted from the model by Richard
