### ISSUE TITLE
Delete of Stereotype FDF_HighlevelFunction & FunctionalArea

### ISSUE THREAD

**Issue by AustriaTech** [FRAME-NEXT/FRAME#7]
In bilateral Meeting with me(Ben) and Richard, the Richard indetified the Stereotype FDF_HighlevelFunction & FunctionalArea as not necessary.
So the proposal is to delete them and use only one FDF_LowLevelFunction

Does someone has another point?
![grafik](https://user-images.githubusercontent.com/60388823/100354357-59ca0380-2ff0-11eb-89a0-09ee333c942c.png)

**Comment by mertaksac** [comment]
please see issue #20 for another question related to Data Flow stereotypes

**Comment by mertaksac** [comment]
There is now only one Data Flow stereotype (architecture tool V4.44). This issue will be closed.
